# Notes:
# - Minimal appveyor.yml file is an empty file. All sections are optional.
# - Indent each level of configuration with 2 spaces. Do not use tabs!
# - All section names are case-sensitive.
# - Section names should be unique on each level.

#---------------------------------#
#  general configuration          #
#---------------------------------#

# version format
version: '{branch}-{build}'

# Do not build on tags (GitHub only)
skip_tags: true

# manual mode
branches:
  except:
    - /.*/


#---------------------------------#
#  environment configuration      #
#---------------------------------#

# environment variables
# build system info: https://www.appveyor.com/docs/installed-software
os: Visual Studio 2015

environment:
  REPO_DIR: &REPO_DIR c:\project  # directory created by appveyor

  FBSDK_DIR: c:\fbsdk
  FBSDK_VERSION: 2015-08-03

  SOL_FILE: foo_xspf_1.sln
  MSBUILD_CMD: /m /p:Configuration=Release

# clone directory
clone_folder: *REPO_DIR

install:
  - 'cd \'
  - powershell -Command "& { $foo = 'https://www.foobar2000.org'; $wc = New-Object Net.WebClient; $wc.DownloadString( $foo + '/SDK' ) -match '/getfile/.+/SDK-2015-08-03.zip'; $path = $matches[0] -replace 'getfile' , 'files'; $wc.DownloadFile( $foo + $path , 'fbsdk.zip' ); }" > nul
  - '7z x "fbsdk.zip" -o"%FBSDK_DIR%" > nul'


#---------------------------------#
#  build configuration            #
#---------------------------------#

# scripts to run before build
before_build:
  # git submodules
  - 'cd "%REPO_DIR%"'
  - 'git submodule update --init --remote --depth 1 --recursive'

  # copy foobar2000 SDK
  - 'cd \'
  - 'robocopy "%FBSDK_DIR%" "%REPO_DIR%\lib\foobar2000_sdk" /E > nul & exit 0'

  # replace project files
  - 'copy /Y "%REPO_DIR%\lib\vcxproj\tinyxml2.vcxproj" "%REPO_DIR%\lib\tinyxml2\tinyxml2"'
  - 'copy /Y "%REPO_DIR%\lib\vcxproj\foobar2000_component_client.vcxproj" "%REPO_DIR%\lib\foobar2000_sdk\foobar2000\foobar2000_component_client"'
  - 'copy /Y "%REPO_DIR%\lib\vcxproj\foobar2000_SDK.vcxproj" "%REPO_DIR%\lib\foobar2000_sdk\foobar2000\SDK"'
  - 'copy /Y "%REPO_DIR%\lib\vcxproj\foobar2000_sdk_helpers.vcxproj" "%REPO_DIR%\lib\foobar2000_sdk\foobar2000\helpers"'
  - 'copy /Y "%REPO_DIR%\lib\vcxproj\pfc.vcxproj" "%REPO_DIR%\lib\foobar2000_sdk\pfc"'

# to run your custom scripts instead of automatic MSBuild
build_script:
  - 'cd "%REPO_DIR%"'
  - 'msbuild %SOL_FILE% %MSBUILD_CMD%'

# scripts to run before deployment
after_build:
  # prepare for artifacts packaging
  - 'cd "%REPO_DIR%"'
  - 'copy "%REPO_DIR%\bin\Release\foo_xspf_1.dll" "%REPO_DIR%"'  # the artifact must reside at the source repo root
  - '7z a -tzip -mx9 "foo_xspf_1.fb2k-component" "foo_xspf_1.dll"'
  - 'powershell -Command "& { $hash = (Get-FileHash -Algorithm SHA1 "foo_xspf_1.fb2k-component").hash.ToString().toLower(); Write-Host $hash " *foo_xspf_1.fb2k-component"; }" > "foo_xspf_1.fb2k-component.sha1"'


#---------------------------------#
#  tests configuration            #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#  artifacts configuration        #
#---------------------------------#

artifacts:
  - path: foo_xspf_1.fb2k-component
    name: plugin
  - path: foo_xspf_1.fb2k-component.sha1
    name: checksum
